### ISSUE TITLE
hey you guys going to update for the new shows?

### ISSUE THREAD

**Issue by r3k2** [the7erm/mycroft-skill-jupiter-broadcasting#2]
like ask noah etc..

**Comment by the7erm** [comment]
@ChrisFernandez ask Noah has been added. Fixed a few bugs while I was in there, and modified everything to work with `mycroft.conf`

**Comment by r3k2** [comment]
@the7erm awesome thanks! yeah they changed/terminated a bunch of programs.. I will msm the skill and try it tonight. thank you.
